idx = round(CF(:,2)*a/60)+ round(CF(:,3)*a/60)*3;
for i = 1:3
    for j = 1:3
        annotation('textbox', ...
            [(i-1)/3, (j)/3-0.1 0.1 0.1], ...
        'String', length(find(idx == (j-2)*3+(i-2))), ...
        'EdgeColor', 'k', ...
        'BackgroundColor','w',...
        'HorizontalAlignment', 'left', ...
        'FontSize', 16);
    end
end